# Site settings
title: Danica Yong | Portfolio
description: My personal portfolio website.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Danica Yong
user_description: I am currently a third year statistics student from UNSW. I am passionate about Marketing and Data. My hobbi
user_title: Aspiring Data Scientist
email: danica_safina@yahoo.com
github_username: dannikaaa

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
